#!/usr/bin/env python3
"""
Generate the Hausa audio library with YarnGPT-local.

WHY THIS IS A BUILD STEP, NOT A RUNTIME CALL
--------------------------------------------
YarnGPT-local is a 0.4B-parameter transformer (a SmolLM2-360M finetune) paired
with a WavTokenizer decoder. It needs a GPU to run at any usable speed. The
tablets this app targets are low-end Android devices, and the app's first
requirement (PRD FR-5.1) is that everything works with no connection at all.

So the model does not ship in the app and is not called from it. It is run
once, here, on a machine with a GPU; the resulting clips are bundled as assets
and played back locally. That is also what the PRD always described — a
recorded Hausa audio library — and it means narration costs a file read at
runtime instead of a network round trip a rural classroom cannot make.

BEFORE YOU RUN THIS: LICENCE
----------------------------
YarnGPT-local is published under CC BY-NC-SA 4.0 — non-commercial, share-alike.
Two things follow and someone with authority has to decide them, not this
script:

  1. Non-commercial. If Hanyar Ilimi is distributed free by an NGO or a
     ministry, this is very likely fine. If it is ever sold, bundled with a
     paid device, or licensed to a commercial partner, it is not.
  2. Share-alike. Whether audio generated by an NC-SA model is a "derivative"
     that inherits the licence is genuinely unsettled, and reasonable lawyers
     disagree. Ask before shipping, not after.

YarnGPT was acquired by Bluechip Technologies in June 2026, so the licence and
terms may have changed since this script was written — check the model card
before a production run.

The alternative, if either answer comes back badly, is the same pipeline
pointed at recordings by a human Hausa speaker. Nothing downstream of this
script cares how the WAV files were made.

QUALITY NOTES FROM THE MODEL CARD
---------------------------------
  - Output "is sometimes very fast and might need some post-processing." For
    children learning to decode words this is not cosmetic, so every clip is
    slowed and the rate is configurable per run.
  - The model "doesn't take intonations into account which sometimes leads to
    mispronunciation." Hausa is tonal. Some words will be wrong. Every clip
    must be listened to by a Hausa speaker before it reaches a child — use
    --review to produce a checklist.

USAGE
-----
On a GPU machine (Colab is what the model card assumes):

    git clone https://github.com/saheedniyi02/yarngpt.git
    pip install outetts==0.2.3 uroman torchaudio pydub transformers
    wget https://huggingface.co/novateur/WavTokenizer-medium-speech-75token/resolve/main/wavtokenizer_mediumdata_frame75_3s_nq1_code4096_dim512_kmeans200_attn.yaml
    gdown 1-ASeEkrn4HY49yZWHTASgfGFNXdVnLTt   # wavtokenizer checkpoint

    python tools/generate_audio.py \
        --wav-config wavtokenizer_..._attn.yaml \
        --wav-model  wavtokenizer_large_speech_320_24k.ckpt \
        --voice hausa_female1

Then copy `assets/audio/ha/` back into the repo and run
`node tools/build_clip_registry.mjs`.
"""
from __future__ import annotations

import argparse
import json
import shutil
import subprocess
import sys
from pathlib import Path

MANIFEST = Path("assets/audio/manifest.json")
OUT_DIR = Path("assets/audio/ha")

# The model card lists four Hausa voices. One voice for the whole app: a child
# should hear the same person throughout, the way they would with one teacher.
HAUSA_VOICES = ["hausa_female1", "hausa_female2", "hausa_male1", "hausa_male2"]


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(description="Generate Hausa lesson audio with YarnGPT-local.")
    p.add_argument("--wav-config", required=True, help="WavTokenizer .yaml config path")
    p.add_argument("--wav-model", required=True, help="WavTokenizer .ckpt weights path")
    p.add_argument("--model", default="saheedniyi/YarnGPT-local")
    p.add_argument("--voice", default="hausa_female1", choices=HAUSA_VOICES)
    p.add_argument("--speed", type=float, default=0.9,
                   help="Playback rate applied after generation. The model runs fast; "
                        "0.9 is the model card's own suggestion, 0.85 suits younger children.")
    p.add_argument("--temperature", type=float, default=0.1)
    p.add_argument("--repetition-penalty", type=float, default=1.1)
    p.add_argument("--num-beams", type=int, default=4)
    p.add_argument("--max-length", type=int, default=4000)
    p.add_argument("--limit", type=int, default=0, help="Only generate the first N missing clips (for a trial run).")
    p.add_argument("--only", default="",
                   help="Comma-separated source prefixes to generate, e.g. 'phrase,number'. "
                        "Doing 'phrase,number' first (about 40 clips) makes every screen the "
                        "child navigates speak Hausa, which is the fastest audible result.")
    p.add_argument("--force", action="store_true", help="Regenerate clips that already exist.")
    p.add_argument("--keep-wav", action="store_true", help="Keep the intermediate 24kHz WAV files.")
    p.add_argument("--review", action="store_true",
                   help="Write a review checklist instead of generating. Use after a run.")
    return p.parse_args()


def load_manifest() -> list[dict]:
    if not MANIFEST.exists():
        sys.exit(f"{MANIFEST} not found. Run `node tools/extract_strings.mjs` first.")
    return json.loads(MANIFEST.read_text(encoding="utf-8"))["clips"]


def write_review_sheet(clips: list[dict]) -> None:
    """A checklist for the Hausa speaker who has to sign the library off."""
    out = Path("assets/audio/REVIEW.md")
    present = {p.stem for p in OUT_DIR.glob("*.m4a")} if OUT_DIR.exists() else set()
    lines = [
        "# Hausa audio review",
        "",
        "Every clip below was generated by a model that does not model tone. Hausa is",
        "tonal, so some of these will be wrong in ways that matter to a child learning",
        "to read. Listen to each one and tick it, or note what is wrong.",
        "",
        "Play a clip with: `afplay assets/audio/ha/<id>.m4a` (macOS) or",
        "`ffplay -nodisp -autoexit assets/audio/ha/<id>.m4a`.",
        "",
        "| ✓ | Clip | Text | Notes |",
        "| - | ---- | ---- | ----- |",
    ]
    for c in clips:
        mark = " " if c["id"] in present else "—"
        text = c["text"].replace("|", "\\|")
        lines.append(f"| [{mark}] | `{c['id']}` | {text} | |")
    out.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote {out} — {len(clips)} lines to review.")


def encode(wav_path: Path, m4a_path: Path, speed: float) -> None:
    """
    Slow the clip down, pad it, and encode it small.

    AAC at 48k mono is about 6 KB per second of speech; the whole library lands
    well under 10 MB, which matters when it ships inside the APK.

    The `apad` at the end is not cosmetic. AAC encodes in fixed-size frames, so
    a clip ending mid-frame gets its tail dropped by many Android decoders --
    which lands exactly on the final consonant of a word. In a literacy app
    that is the difference between "biyar" and "biya". A third of a second of
    silence pushes the real audio clear of the frame boundary.
    """
    if not shutil.which("ffmpeg"):
        sys.exit("ffmpeg is required for post-processing. Install it and re-run.")
    subprocess.run(
        [
            "ffmpeg", "-y", "-loglevel", "error",
            "-i", str(wav_path),
            # atempo slows without changing pitch — resampling would drop the
            # voice into a register that does not sound like the speaker.
            "-filter:a", (
                f"atempo={speed},"
                "dynaudnorm=f=200:g=5,"
                "silenceremove=start_periods=1:start_threshold=-45dB:start_silence=0.05,"
                "apad=pad_dur=0.35"
            ),
            "-c:a", "aac", "-b:a", "48k", "-ac", "1", "-ar", "24000",
            str(m4a_path),
        ],
        check=True,
    )


def main() -> None:
    args = parse_args()
    clips = load_manifest()
    OUT_DIR.mkdir(parents=True, exist_ok=True)

    if args.review:
        write_review_sheet(clips)
        return

    if args.only:
        wanted = tuple(p.strip() for p in args.only.split(",") if p.strip())
        clips = [c for c in clips if any(s.startswith(wanted) for s in c["sources"])]
        print(f"Filtered to {len(clips)} clips matching: {', '.join(wanted)}")

    pending = [c for c in clips if args.force or not (OUT_DIR / f"{c['id']}.m4a").exists()]
    if args.limit:
        pending = pending[: args.limit]

    if not pending:
        print(f"Nothing to do — all {len(clips)} clips are already recorded.")
        return

    print(f"{len(pending)} of {len(clips)} clips to generate, voice={args.voice}, speed={args.speed}")

    # Imported here so `--review` works on a machine with no GPU stack.
    import torch  # noqa: F401
    import torchaudio
    from transformers import AutoModelForCausalLM
    from yarngpt.audiotokenizer import AudioTokenizerForLocal

    audio_tokenizer = AudioTokenizerForLocal(args.model, args.wav_model, args.wav_config)
    model = AutoModelForCausalLM.from_pretrained(args.model, torch_dtype="auto").to(audio_tokenizer.device)

    wav_dir = OUT_DIR / "_wav"
    wav_dir.mkdir(exist_ok=True)

    failures: list[tuple[str, str]] = []

    for i, clip in enumerate(pending, 1):
        text, clip_id = clip["text"], clip["id"]
        print(f"[{i}/{len(pending)}] {clip_id}  {text[:60]}")
        try:
            prompt = audio_tokenizer.create_prompt(text, lang="hausa", speaker_name=args.voice)
            input_ids = audio_tokenizer.tokenize_prompt(prompt)
            output = model.generate(
                input_ids=input_ids,
                temperature=args.temperature,
                repetition_penalty=args.repetition_penalty,
                num_beams=args.num_beams,
                max_length=args.max_length,
            )
            audio = audio_tokenizer.get_audio(audio_tokenizer.get_codes(output))

            wav_path = wav_dir / f"{clip_id}.wav"
            torchaudio.save(str(wav_path), audio, sample_rate=24000)
            encode(wav_path, OUT_DIR / f"{clip_id}.m4a", args.speed)
            if not args.keep_wav:
                wav_path.unlink(missing_ok=True)
        except Exception as exc:  # a single bad line must not lose the whole run
            print(f"    FAILED: {exc}")
            failures.append((clip_id, text))

    if not args.keep_wav:
        shutil.rmtree(wav_dir, ignore_errors=True)

    done = len(list(OUT_DIR.glob("*.m4a")))
    print(f"\nRecorded {done} of {len(clips)} clips.")
    if failures:
        print(f"{len(failures)} failed — re-run to retry just these:")
        for clip_id, text in failures:
            print(f"  {clip_id}  {text[:60]}")

    print("\nNext:")
    print("  1. node tools/build_clip_registry.mjs   # bundle them into the app")
    print("  2. python tools/generate_audio.py --review   # checklist for a Hausa speaker")
    print("\nNothing generated here should reach a child before a Hausa speaker has heard it.")


if __name__ == "__main__":
    main()
